### PR TITLE
Fixes

### LINKED ISSUE #350: Recommendations Package Causes Error Due to options.emitMetric being undefined.
I don't have access to the repo, but was going to submit a PR such as below:
screen shot 2018-10-03 at 4 03 30 pm

Below emitCustomGoal I would like to add emitMetric due to the fact that the new recommendation package uses this and when building using the CLI, you will get an error due to this method being undefined. [usage of emitMetric in the shown and clicked methods](https://github.com/QubitProducts/recommendations/blob/master/index.js)

Any chance this could be added or I could get access to submit a PR? Thanks!

### PR DESCRIPTION
**Pull request by samuelfullerthomas**
fixes #350 

- lodash merge -> Object.assign
- add emitMetric to the api

@nkbelow

### CODE REVIEW

File: src/lib/merge-pkg.js [hunk 1]
```diff
@@ -7,7 +7,7 @@ module.exports = function mergePkg (localPkg, remotePkg) {
   if (typeof localPkg === 'string') localPkg = JSON.parse(localPkg)
   if (typeof remotePkg === 'string') remotePkg = JSON.parse(remotePkg)
   const pkg = { ...localPkg, ...remotePkg }
-  _.set(pkg, 'meta', _.merge({}, localPkg.meta, remotePkg.meta) || {})
+  _.set(pkg, 'meta', Object.assign({}, localPkg.meta, remotePkg.meta) || {})
```
Comment (alexjesp) [inline src/lib/merge-pkg.js]: You can just do `_.set(pkg, 'meta', { ...localPkg.meta, ...remotePkg.meta })` no?
